apiVersion: batch/v1
kind: Job
metadata:
  name: ml-resource-constrained
spec:
  template:
    spec:
      containers:
      - name: ml-worker
        image: ml-workload:v1
        imagePullPolicy: Never
        command: ["python"]
        args: ["src/train_rf.py"]
        resources:
          requests:
            cpu: "250m"    # Only 0.25 of a CPU core
            memory: "256Mi"
          limits:
            cpu: "500m"    # Max 0.5 CPU - This will slow it down!
            memory: "512Mi"
      restartPolicy: Never
  backoffLimit: 0