apiVersion: batch/v1
kind: Job
metadata:
  name: ml-node-affinity
spec:
  template:
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              # Only runs on nodes you have labeled 'hardware=high-perf'
              - key: hardware
                operator: In
                values:
                - high-perf
      containers:
      - name: ml-worker
        image: ml-workload:v1
        imagePullPolicy: Never
        command: ["python"]
        args: ["src/train_rf.py"]
      restartPolicy: Never